language: node_js
node_js:
  - 12
install:
  - cd frontend
  - npm install
script:
  - npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: "talk-to-me.com"
  acl: public_read
  region: "us-west-1"
  skip_cleanup: true
  local_dir: build